// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGA.Api.Data;

#nullable disable

namespace SIGA.Api.Data.Migrations
{
    [DbContext(typeof(SigaDbContext))]
    [Migration("20260818144043_InicialInventarioTi")]
    partial class InicialInventarioTi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SIGA.Api.Domain.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short?>("AnoAquisicao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("GarantiaAte")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NotaFiscalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patrimonio")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSerie")
                        .IsUnique()
                        .HasFilter("NumeroSerie IS NOT NULL");

                    b.HasIndex("Patrimonio")
                        .IsUnique()
                        .HasFilter("Patrimonio IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("Tipo");

                    b.ToTable("equipamento", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SIGA.Api.Domain.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistradoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RegistradoPor")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("historico", (string)null);
                });

            modelBuilder.Entity("SIGA.Api.Domain.Computador", b =>
                {
                    b.HasBaseType("SIGA.Api.Domain.Equipamento");

                    b.Property<int?>("ArmazenamentoGb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Processador")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<short?>("RamGb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SistemaOperacional")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtipo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoArmazenamento")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.ToTable("computador", (string)null);
                });

            modelBuilder.Entity("SIGA.Api.Domain.DispositivoRede", b =>
                {
                    b.HasBaseType("SIGA.Api.Domain.Equipamento");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoMac")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<short?>("NumPortas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtipo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersaoFirmware")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasIndex("EnderecoMac")
                        .IsUnique()
                        .HasFilter("EnderecoMac IS NOT NULL");

                    b.ToTable("dispositivo_rede", (string)null);
                });

            modelBuilder.Entity("SIGA.Api.Domain.Impressora", b =>
                {
                    b.HasBaseType("SIGA.Api.Domain.Equipamento");

                    b.Property<bool>("Colorida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conexao")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContadorPaginas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoImpressao")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.ToTable("impressora", (string)null);
                });

            modelBuilder.Entity("SIGA.Api.Domain.Historico", b =>
                {
                    b.HasOne("SIGA.Api.Domain.Equipamento", "Equipamento")
                        .WithMany("Historicos")
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("SIGA.Api.Domain.Computador", b =>
                {
                    b.HasOne("SIGA.Api.Domain.Equipamento", null)
                        .WithOne()
                        .HasForeignKey("SIGA.Api.Domain.Computador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGA.Api.Domain.DispositivoRede", b =>
                {
                    b.HasOne("SIGA.Api.Domain.Equipamento", null)
                        .WithOne()
                        .HasForeignKey("SIGA.Api.Domain.DispositivoRede", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGA.Api.Domain.Impressora", b =>
                {
                    b.HasOne("SIGA.Api.Domain.Equipamento", null)
                        .WithOne()
                        .HasForeignKey("SIGA.Api.Domain.Impressora", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGA.Api.Domain.Equipamento", b =>
                {
                    b.Navigation("Historicos");
                });
#pragma warning restore 612, 618
        }
    }
}
